services:
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./backend/src/
          target: /usr/local/app/src
        - action: rebuild
          path: ./backend/package.json
  client:
    build:
      context: ./client
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./client/src/
          target: /usr/local/app/src
        - action: rebuild
          path: ./client/package.json
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yenno
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data:
